name: go_test
on:
  pull_request:
    types: [opened, synchronize]
defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=profile.cov ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          pwd
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
          ls -la
