name: go_test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          go env
          export PATH=$PATH:$(go env GOPATH)/bin
          go test -v -covermode=atomic -coverprofile=coverage.out ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Read status
        run: |
          go env
          ls -la
          pwd
          echo $GOPATH
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.githubtoken }}
          path-to-lcov: coverage.lcov
