name: go_test
on:
  pull_request:
    types: [opened, synchronize]
defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: app/coverage.out
          outfile: coverage.lcov
